### ISSUE TITLE
Terminal becomes green

### ISSUE THREAD

**Issue by mks-h** [edfloreshz/sensei#11]
**Describe the bug**
After printing a massage, the terminal stays green. You've forgotten to change the colour back to normal after printing.

**To Reproduce**
1. Run it

**Screenshots**
![image](https://user-images.githubusercontent.com/51861383/167747302-70434b11-3713-4d90-a155-c5eb57d6489f.png)

**Comment by edfloreshz** [comment]
Thanks for the bug report, I'll look into that.
