### ISSUE TITLE
Support opening local crates first

### ISSUE THREAD

**Issue by maxpolun** [edfloreshz/sensei#3]
Currently sensei only opens documentation on crates.io, but a nice additional feature would be to
1. detect if you're in a cargo project
2. see if there's documentation for the requested crate in the `target/` folder of this cargo project (have to keep workspaces in mind here)
3. open the local copy of the documentation for the requested crate if it's there
4. open crates.io if either there's no local documentation, or if we're not in a cargo project

**Comment by edfloreshz** [comment]
Implemented in [732f870](https://github.com/edfloreshz/sensei/commit/732f870c032c5015bfd4d53e293fd88b5538bd44) as an option given that versioning is virtually impossible without having to download every single version before opening it and querying is not possible given that the browser cannot process the `?search=<query>` parameter.

When using -l, --local the program tries to open local documentation, if there's no success, it will open the online version.
