### ISSUE TITLE
Open doc of a crate with version specified in project's cargo.toml

### ISSUE THREAD

**Issue by categulario** [edfloreshz/sensei#7]
Use case:

I'm writing a rust lib/bin and I depend on `foo`. In my cargo.toml I have `foo = "x.y.z"` specified. I would like `sensei` to open that specific version of the crate without much trouble. Perhaps a --cargo flag?

**Comment by edfloreshz** [comment]
I could add a `-t|--this` flag to make `sensei` search for that crate's version in `Cargo.toml` and open it. 

e.g. `sensei rand --this` or `sensei -t rand`.

**Comment by categulario** [comment]
Perhaps it would be more natural with -c --cargo? Just because "this" also
makes me think about the crate I'm working on, but thats the task of the
--local flag

**Comment by edfloreshz** [comment]
I feel like both are missing the point.

Perhaps something like `-lv|--local-version`, what do you think?

**Comment by categulario** [comment]
I really think --cargo (or perhaps --from-cargo but that's too long) at
least tells you where it is coming from unambiguously.

It just occurred to me that -m --manifest could work (since cargo is Rust's
manifest file). Accompanied with a good help("") message

**Comment by edfloreshz** [comment]
Okay that has a nice ring to it, I'll take a look at it and try to implement it.

**Comment by edfloreshz** [comment]
Resolved in b976465
